using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using AutoRental.ViewModels.Admin;
using Service.Implementations;
using Service.Interfaces;
using DataAccessObjects.Repositories.Implementations;
using DataAccessObjects.Repositories.Interfaces;

namespace AutoRental.View.Admin
{
    /// <summary>
    /// Interaction logic for VoucherManagementWindow.xaml
    /// </summary>
    public partial class VoucherManagementWindow : Window
    {
        public VoucherManagementWindow()
        {
            InitializeComponent();
            
            // Setup Services (Dependency Injection)
            IDiscountRepository discountRepo = new DiscountRepository();
            IDiscountService discountService = new DiscountService(discountRepo);
            
            // Create and set ViewModel
            var viewModel = new VoucherManagementViewModel(discountService);
            this.DataContext = viewModel;
        }

        private void voucherDataGrid_Loaded(object sender, RoutedEventArgs e)
        {
            // Ensure auto-generation is off, in case it's being overridden or re-enabled
            voucherDataGrid.AutoGenerateColumns = false;
            
            // Clear any auto-generated columns that might have been added
            // This is a defensive measure to ensure only explicitly defined columns are shown.
            var autoGeneratedColumns = voucherDataGrid.Columns.Where(c => !c.IsReadOnly).ToList();
            foreach (var column in autoGeneratedColumns)
            {
                // Check if the column header matches common auto-generated property names
                // that might conflict with explicitly defined columns or should be hidden.
                if (column.Header.ToString().Contains("Discount") || 
                    column.Header.ToString().Contains("Booking") ||
                    column.Header.ToString().Contains("Bookings"))
                {
                    voucherDataGrid.Columns.Remove(column);
                }
            }
        }
    }
}
